force-app/main/default/objects/Quote/recordTypes/Bon_de_commande.recordType-meta.xml
<RecordType>
    <fullName>Bon_de_commande</fullName>
    <active>true</active>
    <label>Bon de commande</label>
</RecordType>

force-app/main/default/objects/Quote/recordTypes/Proforma.recordType-meta.xml
<RecordType>
    <fullName>Proforma</fullName>
    <active>true</active>
    <label>Proforma</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/Destockage__c.field-meta.xml
<CustomField>
    <fullName>Destockage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Destockage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Droit_Proportionnel__c.field-meta.xml
<CustomField>
    <fullName>Droit_Proportionnel__c</fullName>
    <label>Droit Proportionnel (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Frais_d_immatriculation__c.field-meta.xml
<CustomField>
    <fullName>Frais_d_immatriculation__c</fullName>
    <label>Frais d&apos;immatriculation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/N_de_plaque_VO__c.field-meta.xml
<CustomField>
    <fullName>N_de_plaque_VO__c</fullName>
    <label>N° de plaque VO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Prix_de_vente_CEM__c.field-meta.xml
<CustomField>
    <fullName>Prix_de_vente_CEM__c</fullName>
    <label>Prix de vente CEM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Prix_de_vente_CEM_hors_DP__c.field-meta.xml
<CustomField>
    <fullName>Prix_de_vente_CEM_hors_DP__c</fullName>
    <label>Prix de vente CEM (hors DP)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Prix_public_produit_TTC__c.field-meta.xml
<CustomField>
    <fullName>Prix_public_produit_TTC__c</fullName>
    <label>Prix public produit TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Prix_public_TTC__c.field-meta.xml
<CustomField>
    <fullName>Prix_public_TTC__c</fullName>
    <label>Prix public TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Prix_Total_Options_TTC__c.field-meta.xml
<CustomField>
    <fullName>Prix_Total_Options_TTC__c</fullName>
    <label>Prix Total Options TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Prix_vente_Options_TTC__c.field-meta.xml
<CustomField>
    <fullName>Prix_vente_Options_TTC__c</fullName>
    <label>Prix vente Options TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Prix_vente_produit_TTC__c.field-meta.xml
<CustomField>
    <fullName>Prix_vente_produit_TTC__c</fullName>
    <label>Prix vente produit TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Promo__c.field-meta.xml
<CustomField>
    <fullName>Promo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Anouar : j&apos;ai changé le label du champ</description>
    <inlineHelpText>Anouar : j&apos;ai changé le label du champ</inlineHelpText>
    <label>Prix spécial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Remise_destockage_promo__c.field-meta.xml
<CustomField>
    <fullName>Remise_destockage_promo__c</fullName>
    <label>Remise destockage/promo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Remise_Plancher_VO__c.field-meta.xml
<CustomField>
    <fullName>Remise_Plancher_VO__c</fullName>
    <label>Remise Plancher VO</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/AX001_AddBDC.cls
public with sharing class AX001_AddBDC {
    @InvocableMethod
    public static  list<Quote> CreationBonDeCommande(list<string> oppIds){

        //creation de BDC
        String oppId = oppIds[0];
        Opportunity opp = [SELECT id,Name FROM Opportunity  WHERE Id =: oppId];

        Id recordTypeId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName()
        .get('Bon_de_commande').getRecordTypeId();
        Quote bdc = new quote(Name = 'BDC-'+opp.Name,
        RecordTypeId =recordTypeId,OpportunityId=oppId);
        User currentUser = [SELECT id,Showroom__c
        FROM User
        WHERE id=: UserInfo.getUserId()];

        list<User> approbateurs = [SELECT id,UserRole.DeveloperName, Email 
        FROM User
        WHERE (Showroom__c =: currentUser.Showroom__c 
        And (UserRole.DeveloperName LIKE '%ADV%' OR 
        UserRole.DeveloperName LIKE '%Chef_de_ventes%' OR
        UserRole.DeveloperName LIKE '%Directeur_de_site%'))
        OR    UserRole.DeveloperName = 'National' OR UserRole.DeveloperName = 'Finance'
        OR    UserRole.DeveloperName = 'Chef_de_service_ordering' OR UserRole.DeveloperName = 'Directeur_Commercial'
        OR    UserRole.DeveloperName = 'Responsable_Achat_VO'];



        for (User user : approbateurs) {
            if(user.UserRole.DeveloperName == 'National'){
                bdc.National__c = user.Id;
                bdc.National_Email__c = user.Email;
            }else if(user.UserRole.DeveloperName.contains('ADV')){
                bdc.ADV_Ville__c = user.Id;
                bdc.ADV_Email__c = user.Email;
            }else if(user.UserRole.DeveloperName.contains('Chef_de_ventes')){
                bdc.CDV__c = user.Id;
                bdc.CDV_Email__c = user.Email;
            }else if(user.UserRole.DeveloperName.contains('Directeur_de_site')){
                bdc.DS__c = user.Id;
                bdc.DS_Email__c = user.Email;
            }else if(user.UserRole.DeveloperName == 'Finance'){
                bdc.Finance__c = user.Id;
            }else if(user.UserRole.DeveloperName == 'Chef_de_service_ordering'){
                bdc.Chef_de_service_ordering__c = user.Id;
            }else if(user.UserRole.DeveloperName == 'Directeur_Commercial'){
                bdc.Directeur_Commercial__c = user.Id;
            }else if(user.UserRole.DeveloperName == 'Responsable_Achat_VO'){
                bdc.Responsable_Achat_VO__c = user.Id;
            }

        }
        insert bdc;
        

       QuoteLineItem quoteLineItem = [SELECT id,Destockage__c,Promo__c,Discount,UnitPrice,Prix_de_vente_CEM_hors_DP__c, product2Id, PricebookEntryId,
       Prix_de_vente_CEM__c, Prix_plancher_VO_TTC__c, Droit_Proportionnel__c,
       Prix_Total_Options_TTC__c,Prix_vente_Options_TTC__c,Prix_public_TTC__c, Frais_d_immatriculation__c, 
       Prix_public_produit_TTC__c,Prix_vente_produit_TTC__c,N_de_plaque_VO__c,
       Remise_plancher_VO__c,Quantity,Remise_destockage_promo__c,OpportunityLineItemId
       FROM QuoteLineItem 
       WHERE Quote.status = 'Approuvé' and Quote.OpportunityId =: oppId and Quote.recordType.DeveloperName = 'Proforma'];

       QuoteLineItem bdcLineItem = quoteLineItem.clone(false, false, false, false);
       bdcLineItem.QuoteId = bdc.id;

       insert bdcLineItem; 

       return new list<Quote>{bdc};
    }
}